import { describe, expect, it } from "vitest";
import { StashError, statusForCode } from "./errors.js";
import {
  BODY_LIMIT_BYTES,
  DIFF_MAX_BYTES,
  DIFF_MAX_EDIT_LENGTH,
  DIFF_TIMEOUT_MS,
  IDEMPOTENCY_KEY_MAX_CHARS,
  IDEMPOTENCY_TTL_DAYS,
  LIST_LIMIT_DEFAULT,
  LIST_LIMIT_MAX,
  MAX_AUTHOR_BYTES,
  MAX_BODY_BYTES,
  MAX_IMPORT_VERSIONS,
  MAX_MESSAGE_BYTES,
  MAX_META_BYTES,
  MAX_PATH_BYTES,
  R2_SPILL_BYTES,
  JSON_INLINE_MAX_BYTES,
  D1_INLINE_MAX_BYTES,
  D1_INLINE_MAX_BYTES_CEILING,
  HTTP_REQUEST_MAX_BYTES,
  SINGLE_UPLOAD_MAX_BYTES,
  MAX_FILE_BYTES,
  MAX_FILE_BYTES_CEILING,
  MULTIPART_PART_BYTES,
  MULTIPART_PRODUCTION_MIN_PART_BYTES,
  MAX_MULTIPART_PARTS,
  MAX_OPEN_UPLOAD_SESSIONS,
  MAX_RESERVED_UPLOAD_BYTES,
  UPLOAD_SESSION_TTL_SECONDS,
} from "./limits.js";

it("pins every architecture limit", () => {
  expect({
    MAX_BODY_BYTES,
    MAX_PATH_BYTES,
    MAX_META_BYTES,
    MAX_AUTHOR_BYTES,
    MAX_MESSAGE_BYTES,
    LIST_LIMIT_DEFAULT,
    LIST_LIMIT_MAX,
    DIFF_MAX_BYTES,
    R2_SPILL_BYTES,
    DIFF_TIMEOUT_MS,
    DIFF_MAX_EDIT_LENGTH,
    IDEMPOTENCY_KEY_MAX_CHARS,
    IDEMPOTENCY_TTL_DAYS,
    BODY_LIMIT_BYTES,
    MAX_IMPORT_VERSIONS,
    JSON_INLINE_MAX_BYTES,
    D1_INLINE_MAX_BYTES,
    D1_INLINE_MAX_BYTES_CEILING,
    HTTP_REQUEST_MAX_BYTES,
    SINGLE_UPLOAD_MAX_BYTES,
    MAX_FILE_BYTES,
    MAX_FILE_BYTES_CEILING,
    MULTIPART_PART_BYTES,
    MULTIPART_PRODUCTION_MIN_PART_BYTES,
    MAX_MULTIPART_PARTS,
    MAX_OPEN_UPLOAD_SESSIONS,
    MAX_RESERVED_UPLOAD_BYTES,
    UPLOAD_SESSION_TTL_SECONDS,
  }).toEqual({
    MAX_BODY_BYTES: 5_000_000,
    MAX_PATH_BYTES: 512,
    MAX_META_BYTES: 4_096,
    MAX_AUTHOR_BYTES: 200,
    MAX_MESSAGE_BYTES: 2_000,
    LIST_LIMIT_DEFAULT: 50,
    LIST_LIMIT_MAX: 200,
    DIFF_MAX_BYTES: 524_288,
    R2_SPILL_BYTES: 524_288,
    DIFF_TIMEOUT_MS: 2_000,
    DIFF_MAX_EDIT_LENGTH: 50_000,
    IDEMPOTENCY_KEY_MAX_CHARS: 200,
    IDEMPOTENCY_TTL_DAYS: 7,
    BODY_LIMIT_BYTES: 33_554_432,
    MAX_IMPORT_VERSIONS: 20,
    JSON_INLINE_MAX_BYTES: 5_000_000,
    D1_INLINE_MAX_BYTES: 524_288,
    D1_INLINE_MAX_BYTES_CEILING: 1_500_000,
    HTTP_REQUEST_MAX_BYTES: 100_000_000,
    SINGLE_UPLOAD_MAX_BYTES: 33_554_432,
    MAX_FILE_BYTES: 100_000_000,
    MAX_FILE_BYTES_CEILING: 1_073_741_824,
    MULTIPART_PART_BYTES: 8_388_608,
    MULTIPART_PRODUCTION_MIN_PART_BYTES: 5_242_880,
    MAX_MULTIPART_PARTS: 10_000,
    MAX_OPEN_UPLOAD_SESSIONS: 8,
    MAX_RESERVED_UPLOAD_BYTES: 500_000_000,
    UPLOAD_SESSION_TTL_SECONDS: 86_400,
  });
});

describe("typed errors", () => {
  it.each([
    ["validation", 400],
    ["unauthorized", 401],
    ["scope", 403],
    ["not-found", 404],
    ["stale", 409],
    ["already-rotated", 409],
    ["token-expired", 409],
    ["gc-busy", 409],
    ["proposal-expired", 409],
    ["proposal-closed", 409],
    ["payload-too-large", 413],
    ["rate-limited", 429],
    ["idempotency-key-reused", 422],
    ["unsupported-representation", 422],
    ["upload-session-not-open", 409],
    ["upload-session-expired", 410],
    ["upload-size-mismatch", 422],
    ["upload-hash-mismatch", 422],
    ["range-not-satisfiable", 416],
    ["internal", 500],
  ] as const)("maps %s", (code, status) => expect(statusForCode(code)).toBe(status));

  it("constructs a StashError with its HTTP status", () => {
    const error = new StashError("file-deleted", "deleted");
    expect(error).toMatchObject({ name: "StashError", code: "file-deleted", status: 404 });
    expect(error.successorId).toBeUndefined();

    const rotated = new StashError(
      "already-rotated",
      "Token was already rotated.",
      undefined,
      "tok_successor",
    );
    expect(rotated).toMatchObject({ status: 409, successorId: "tok_successor" });
  });
});
