/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/stash/wrangler.toml --include-runtime=false workers/stash/worker-configuration.d.ts` (hash: cc2cc08ea8d9f97aa32b05ddb94bc8d2)
interface __BaseEnv_Env {
  BLOBS: R2Bucket;
  DB: D1Database;
  RL_READ: RateLimit;
  RL_WRITE: RateLimit;
  RL_DIFF: RateLimit;
  ALLOWED_ORIGINS: "http://localhost:5173" | "";
  STASH_DELETE_GRACE_DAYS: "30";
  GC_ORPHAN_MIN_AGE_MS: "900000";
  GC_LEASE_TTL_MS: "300000";
  CHANGE_SET_TTL_DAYS: "14";
  STASH_EVENTS_MAX_STREAM_MS: "300000";
  JSON_INLINE_MAX_BYTES: "5000000";
  D1_INLINE_MAX_BYTES: "524288";
  HTTP_REQUEST_MAX_BYTES: "100000000";
  SINGLE_UPLOAD_MAX_BYTES: "33554432";
  MAX_FILE_BYTES: "100000000";
  DIFF_MAX_BYTES: "524288";
  MULTIPART_PART_BYTES: "8388608";
  MAX_OPEN_UPLOAD_SESSIONS: "8";
  MAX_RESERVED_UPLOAD_BYTES: "500000000";
  UPLOAD_SESSION_TTL_SECONDS: "86400";
  STASH_ADMIN_TOKEN: string;
  STASH_EVENTS: DurableObjectNamespace<import("./src/index").StashEvents>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/index");
    durableNamespaces: "StashEvents";
  }
  interface PreviewEnv {
    BLOBS: R2Bucket;
    DB: D1Database;
    RL_READ: RateLimit;
    RL_WRITE: RateLimit;
    RL_DIFF: RateLimit;
    ALLOWED_ORIGINS: "http://localhost:5173";
    STASH_DELETE_GRACE_DAYS: "30";
    GC_ORPHAN_MIN_AGE_MS: "900000";
    GC_LEASE_TTL_MS: "300000";
    CHANGE_SET_TTL_DAYS: "14";
    STASH_EVENTS_MAX_STREAM_MS: "300000";
    JSON_INLINE_MAX_BYTES: "5000000";
    D1_INLINE_MAX_BYTES: "524288";
    HTTP_REQUEST_MAX_BYTES: "100000000";
    SINGLE_UPLOAD_MAX_BYTES: "33554432";
    MAX_FILE_BYTES: "100000000";
    DIFF_MAX_BYTES: "524288";
    MULTIPART_PART_BYTES: "8388608";
    MAX_OPEN_UPLOAD_SESSIONS: "8";
    MAX_RESERVED_UPLOAD_BYTES: "500000000";
    UPLOAD_SESSION_TTL_SECONDS: "86400";
    STASH_ADMIN_TOKEN: string;
    STASH_EVENTS: DurableObjectNamespace<import("./src/index").StashEvents>;
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      | "ALLOWED_ORIGINS"
      | "STASH_DELETE_GRACE_DAYS"
      | "GC_ORPHAN_MIN_AGE_MS"
      | "GC_LEASE_TTL_MS"
      | "CHANGE_SET_TTL_DAYS"
      | "STASH_EVENTS_MAX_STREAM_MS"
      | "JSON_INLINE_MAX_BYTES"
      | "D1_INLINE_MAX_BYTES"
      | "HTTP_REQUEST_MAX_BYTES"
      | "SINGLE_UPLOAD_MAX_BYTES"
      | "MAX_FILE_BYTES"
      | "DIFF_MAX_BYTES"
      | "MULTIPART_PART_BYTES"
      | "MAX_OPEN_UPLOAD_SESSIONS"
      | "MAX_RESERVED_UPLOAD_BYTES"
      | "UPLOAD_SESSION_TTL_SECONDS"
      | "STASH_ADMIN_TOKEN"
    >
  > {}
}
