/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 99b212fa3d16e422cf6af4d77464ef46)
interface __BaseEnv_Env {
  BLOBS: R2Bucket;
  DB: D1Database;
  RL_READ: RateLimit;
  RL_WRITE: RateLimit;
  RL_DIFF: RateLimit;
  ALLOWED_ORIGINS: "http://localhost:5173" | "";
  STASH_DELETE_GRACE_DAYS: "30";
  GC_ORPHAN_MIN_AGE_MS: "900000";
  GC_LEASE_TTL_MS: "300000";
  PROPOSAL_TTL_DAYS: "14";
  STASH_EVENTS_MAX_STREAM_MS: "300000";
  STASH_ADMIN_TOKEN: string;
  STASH_EVENTS: DurableObjectNamespace<import("./src/index").StashEvents>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/index");
    durableNamespaces: "StashEvents";
  }
  interface PreviewEnv {
    BLOBS: R2Bucket;
    DB: D1Database;
    RL_READ: RateLimit;
    RL_WRITE: RateLimit;
    RL_DIFF: RateLimit;
    ALLOWED_ORIGINS: "http://localhost:5173";
    STASH_DELETE_GRACE_DAYS: "30";
    GC_ORPHAN_MIN_AGE_MS: "900000";
    GC_LEASE_TTL_MS: "300000";
    PROPOSAL_TTL_DAYS: "14";
    STASH_EVENTS_MAX_STREAM_MS: "300000";
    STASH_ADMIN_TOKEN: string;
    STASH_EVENTS: DurableObjectNamespace<import("./src/index").StashEvents>;
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      | "ALLOWED_ORIGINS"
      | "STASH_DELETE_GRACE_DAYS"
      | "GC_ORPHAN_MIN_AGE_MS"
      | "GC_LEASE_TTL_MS"
      | "PROPOSAL_TTL_DAYS"
      | "STASH_EVENTS_MAX_STREAM_MS"
      | "STASH_ADMIN_TOKEN"
    >
  > {}
}
