/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 5f7a7c3e57b876f1b1745e4765536ce5)
interface __BaseEnv_Env {
  DB: D1Database;
  RL_READ: RateLimit;
  RL_WRITE: RateLimit;
  RL_DIFF: RateLimit;
  ALLOWED_ORIGINS: "http://localhost:5173" | "";
  STASH_ADMIN_TOKEN: string;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/index");
  }
  interface PreviewEnv {
    DB: D1Database;
    RL_READ: RateLimit;
    RL_WRITE: RateLimit;
    RL_DIFF: RateLimit;
    ALLOWED_ORIGINS: "http://localhost:5173";
    STASH_ADMIN_TOKEN: string;
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<Cloudflare.Env, "ALLOWED_ORIGINS" | "STASH_ADMIN_TOKEN">
  > {}
}
